version: '3.3'
services:
  grafana:
      image: grafana/grafana
      ports:
        - "3000:3000"
      depends_on:
        - mongodb_container
      networks:
        - mongodb_net
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_stub
    restart: always
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    container_name: kafka_stub
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: channelA:1:1, channelB:1:1
  producer:
    build: ./ftpStarbeatArchive
    container_name: microservizio-producer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - kafka
      - mongodb_container
    links:
      - kafka
      - mongodb_container
    environment:
      PRODUCER_TOPIC: channelA
      CONSUMER_TOPIC: channelB
  mongodb_container:
    image: mongo:latest
    environment:
      #This user is created in the admin authentication database and given the role of root, which is a "superuser" role.
      - MONGO_INITDB_ROOT_USERNAME=techtutor
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongodb_net
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    volumes:
      - mongodb_data_container
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb_container
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_USERNAME=techtutor
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_ADMINUSERNAME=techtutor
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb_container
    networks:
      - mongodb_net
volumes:
  mongodb_data_container:

networks:
  mongodb_net:
    driver: bridge